### ISSUE TITLE
请教下F7和vue结合路由的问题

### ISSUE THREAD

**Issue by howyhuang** [lmk123/vue-framework7#1]
大神你好
请教下F7和vue结合路由的问题
我最近在用vue想和F7结合下···想用F7的路由切换效果，不知道怎么用vue实现F7的路由，我尝试一些做法不成功

大神有在关注么

**Comment by lmk123** [comment]
现在 vue-framework7 添加进去的功能都是我在公司项目中用到了的功能。 f7 的路由切换效果实现起来对我来说有点难度，并且公司项目也没用到，所以我不知道自己什么时候会添加这个功能 😂

**Comment by lmk123** [comment]
Hi，回复这个问题只是想让你知道，我刚才更新了 vue-framework7，现在它是基于 Vue 2 的，并且实现了 iOS 的路由切换效果，你可以在这里查看：http://f7.limingkai.cn
