### ISSUE TITLE
组件嵌套太多

### ISSUE THREAD

**Issue by howyhuang** [lmk123/vue-framework7#2]
f7-views f7-view f7-pages f7-page 感觉完全可以一个组件 因为都是一样东西

**Comment by lmk123** [comment]
在实际项目中，我可能会想这样组织结构：

``` html
<!-- app.vue -->
<f7-pages>
  <router-view></router-view>
</f7-pages>
```

``` html
<!-- page.vue -->
<f7-page>
  <f7-searchbar></f7-searchbar>
  <f7-page-content>
    xxxx
  </f7-page-content>
</f7-page>
```

这种情况下，要是将 f7-pages 与 f7-page 合并成一个组件就不合适了。

从目前来看，我也觉得 f7-views 和 f7-view 是可以合并成一个组件的。目前代码并不稳定，等时间长了，如果没有什么不能合并的原因，我就把它们合成一个组件。

**Comment by lmk123** [comment]
Hi, 最近我重构了一遍代码，现在大部分类似于 `f7-views`、`f7-view`、`f7-pages`、`f7-page` 这样的组件都没有了，新版本的 vue-framework7 将专注于提供“组件”而不是简单的 HTML 封装，所以现在你可以直接使用 HTML 了。
